// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    return console.printStackTrace = function() {
      var e, stack;
      e = new Error("dummy");
      stack = e.stack.replace(/^[^\(]+?[\n$]/gm, '').replace(/^\s+at\s+/gm, '').replace(/^Object.<anonymous>\s*\(/gm, '{anonymous}()@').split('\n');
      return console.warn(stack);
    };
  });

}).call(this);
