// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    var Units;
    Units = (function() {

      function Units() {}

      Units.muString = "u";

      Units.ohmString = "ohm";

      Units.getUnitText = function(value, unit, decimalPoints) {
        var absValue;
        if (decimalPoints == null) {
          decimalPoints = 2;
        }
        absValue = Math.abs(value);
        if (absValue < 1e-18) {
          return "0 " + unit;
        }
        if (absValue < 1e-12) {
          return (value * 1e15).toFixed(decimalPoints) + " f" + unit;
        }
        if (absValue < 1e-9) {
          return (value * 1e12).toFixed(decimalPoints) + " p" + unit;
        }
        if (absValue < 1e-6) {
          return (value * 1e9).toFixed(decimalPoints) + " n" + unit;
        }
        if (absValue < 1e-3) {
          return (value * 1e6).toFixed(decimalPoints) + " " + Units.muString + unit;
        }
        if (absValue < 1) {
          return (value * 1e3).toFixed(decimalPoints) + " m" + unit;
        }
        if (absValue < 1e3) {
          return value.toFixed(decimalPoints) + " " + unit;
        }
        if (absValue < 1e6) {
          return (value * 1e-3).toFixed(decimalPoints) + " k" + unit;
        }
        if (absValue < 1e9) {
          return (value * 1e-6).toFixed(decimalPoints) + " M" + unit;
        }
        return (value * 1e-9).toFixed(decimalPoints) + " G" + unit;
      };

      return Units;

    })();
    return Units;
  });

}).call(this);
