// Generated by CoffeeScript 1.8.0
(function() {
  define(['cs!Circuit', 'cs!CircuitState'], function(Circuit, State) {
    return describe("Circuit", function() {
      beforeEach(function() {
        return this.Circuit = new Circuit();
      });
      describe("on initialization", function() {
        it("has no errors", function() {
          this.Circuit.stopMessage === null;
          return this.Circuit.stopElm === null;
        });
        it("has correct initial state", function() {
          return this.Circuit.getState() === State.RUN;
        });
        return it("has a default timestep", function() {
          return this.Circuit.timeStep().should.equal(0.000005);
        });
      });
      describe("should observe", function() {
        return specify("UIContext", function() {
          return this.Circuit.getObservers().should === [];
        });
      });
      describe("has event listeners for", function() {
        specify("onMouseMove (x, y)", function() {});
        specify("onMouseDown (x, y)", function() {});
        return specify("onError (message)", function() {});
      });
      describe("should define events for", function() {
        it("update", function() {
          return Circuit.ON_START_UPDATE !== null;
        });
        it("start", function() {
          return Circuit.ON_START !== null;
        });
        it("pause", function() {
          return Circuit.ON_PAUSE !== null;
        });
        it("complete", function() {});
        it(" added (component)", function() {
          return Circuit.ON_ADD_COMPONENT !== null;
        });
        it("component removed (component)", function() {
          return Circuit.ON_REMOVE_COMPONENT !== null;
        });
        it(" moved (component)", function() {
          return Circuit.ON_MOVE_COMPONENT !== null;
        });
        it(" moved (component)", function() {
          return Circuit.ON_WARNING !== null;
        });
        return it(" moved (component)", function() {
          return Circuit.ON_ERROR !== null;
        });
      });
      describe("has one", function() {
        describe("Canvas", function() {});
        it("has Solver", function() {
          return this.Circuit.Solver !== null;
        });
        return it("has Params Object", function() {});
      });
      return describe("has collection of", function() {
        specify("Voltage Sources", function() {
          return this.Circuit.getVoltageSources().should.be.empty;
        });
        specify("Circuit Components", function() {
          return this.Circuit.getElements().should.be.empty;
        });
        specify("Nodes", function() {
          return this.Circuit.getNodes().should.be.empty;
        });
        return specify("Oscilloscopes", function() {
          this.Circuit.getScopes().should.be.empty;
          specify("GetElmByIdx should return an empty array", function() {});
          return this.Circuit.getElmByIdx(0) === null;
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=circuitTest.js.map
