// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    var Oscilloscope;
    Oscilloscope = (function() {

      function Oscilloscope() {}

      return Oscilloscope;

    })();
    return Oscilloscope;
  });

}).call(this);
