// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    var CommandHistory;
    CommandHistory = (function() {

      function CommandHistory() {
        this.reset();
      }

      CommandHistory.prototype.pushRedo = function(action) {
        return this.redoStack.push(action);
      };

      CommandHistory.prototype.popRedo = function() {
        return this.redoStack.pop();
      };

      CommandHistory.prototype.pushUndo = function(action) {
        return this.undoStack.push(action);
      };

      CommandHistory.prototype.popUndo = function() {
        return this.redoStack.pop();
      };

      CommandHistory.prototype.clearUndo = function() {
        return this.undoStack = new Array();
      };

      CommandHistory.prototype.clearRedo = function() {
        return this.redoStack = new Array();
      };

      CommandHistory.prototype.reset = function() {
        this.undoStack = new Array();
        return this.redoStack = new Array();
      };

      return CommandHistory;

    })();
    return CommandHistory;
  });

}).call(this);
