// Generated by CoffeeScript 1.8.0
(function() {
  var fs, routes;

  fs = require('fs');

  routes = function(app) {
    app.get('/', function(req, res) {
      var circuit_name, circuits;
      circuits = fs.readdirSync("./circuits");
      console.log("loading: " + circuits);
      circuit_name = req.query.circuit;
      return res.render("index.jade", {
        circuits: circuits,
        circuit_name: circuit_name
      });
    });
    app.get('/test', function(req, res) {
      return res.render("test.jade");
    });
    return app;
  };

  module.exports = routes;

}).call(this);

//# sourceMappingURL=routes.js.map
