// Generated by CoffeeScript 1.4.0
(function() {
  var fs, routes;

  fs = require('fs');

  routes = function(app) {
    return app.get('/', function(req, res) {
      var circuit_name, circuits;
      circuits = fs.readdirSync("./circuits");
      console.log("loading: " + circuits);
      circuit_name = req.query.circuit;
      return res.render("index.jade", {
        circuits: circuits,
        circuit_name: circuit_name
      });
    });
  };

  module.exports = routes;

}).call(this);
