// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    var Rectangle;
    Rectangle = (function() {

      function Rectangle(x, y, width, height) {
        this.x = x != null ? x : 0;
        this.y = y != null ? y : 0;
        this.width = width != null ? width : 0;
        this.height = height != null ? height : 0;
      }

      Rectangle.prototype.contains = function(x, y) {
        return x >= this.x && x <= (this.x + this.width) && y >= this.y && (y <= this.y + this.height);
      };

      Rectangle.prototype.equals = function(otherRect) {
        if (otherRect != null) {
          if (otherRect.x === this.x && otherRect.y === this.y && otherRect.width === this.width && otherRect.height === this.height) {
            return true;
          }
        }
        return false;
      };

      Rectangle.prototype.intersects = function(otherRect) {
        var bottomLeftIntersects, bottomRightIntersects, topLeftIntersects, topRightIntersects;
        topLeftIntersects = this.contains(otherRect.x, otherRect.y);
        topRightIntersects = this.contains(otherRect.x + otherRect.width, otherRect.y);
        bottomRightIntersects = this.contains(otherRect.x + otherRect.width, otherRect.y + otherRect.height);
        bottomLeftIntersects = this.contains(otherRect.x, otherRect.y + otherRect.height);
        return topLeftIntersects || topRightIntersects || bottomRightIntersects || bottomLeftIntersects;
      };

      return Rectangle;

    })();
    return Rectangle;
  });

}).call(this);
