// Generated by CoffeeScript 1.4.0
(function() {

  define(['cs!FormatUtils'], function(FormatUtils) {
    return describe("Format utilities", function() {
      specify("NoCommaFormat(x)", function() {
        return FormatUtils.noCommaFormat('1,234,567.99').should.equal('1234567.99');
      });
      specify("addCommas(plainNumber)", function() {
        return FormatUtils.commaFormat('1234567.99').should.equal('1,234,567.99');
      });
      return specify("commaFormat and noCommaFormat are inverse operations", function() {
        var num;
        return num = 123456789;
      });
    });
  });

}).call(this);
