// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['cs!CanvasContext', 'cs!Observer', 'cs!Circuit', 'cs!KeyHandler', 'cs!MouseHandler'], function(CanvasContext, Observer, Circuit, KeyHandler, MouseHandler) {
    var CircuitCanvas;
    CircuitCanvas = (function(_super) {

      __extends(CircuitCanvas, _super);

      function CircuitCanvas(Circuit, CanvasJQueryElm) {
        this.Circuit = Circuit;
        this.CanvasJQueryElm = CanvasJQueryElm;
        this.repaint = __bind(this.repaint, this);

        this.onMouseClick = __bind(this.onMouseClick, this);

        this.onMouseUp = __bind(this.onMouseUp, this);

        this.onMouseDown = __bind(this.onMouseDown, this);

        this.onMouseMove = __bind(this.onMouseMove, this);

        this.getMousePos = __bind(this.getMousePos, this);

        if (this.CanvasJQueryElm) {
          this.Context = new CanvasContext(this.CanvasJQueryElm.get(0));
        }
        this.CanvasJQueryElm.mousemove(this.onMouseMove);
        this.CanvasJQueryElm.mousedown(this.onMouseDown);
        this.CanvasJQueryElm.mouseup(this.onMouseUp);
        this.CanvasJQueryElm.click(this.onMouseClick);
        this.Circuit.addObserver(Circuit.ON_START_UPDATE, this.clear);
        this.Circuit.addObserver(Circuit.ON_RESET, this.clear);
        this.Circuit.addObserver(Circuit.ON_END_UPDATE, this.repaint);
        this.KeyHandler = new KeyHandler();
        this.MouseHandler = new MouseHandler();
      }

      CircuitCanvas.prototype.drawComponents = function() {
        var component, _i, _len, _ref, _results;
        this.clear();
        if (this.Context) {
          _ref = this.Circuit.getElements();
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            component = _ref[_i];
            _results.push(this.drawComponent(component));
          }
          return _results;
        }
      };

      CircuitCanvas.prototype.drawComponent = function(component) {
        if (this.Context) {
          return component.draw(this.Context);
        }
      };

      CircuitCanvas.prototype.drawInfo = function() {
        var bottomTextOffset, ybase;
        bottomTextOffset = 100;
        return ybase = this.Circuit.getCircuitBottom - (15 * 1) - bottomTextOffset;
      };

      CircuitCanvas.prototype.drawWarning = function(context) {
        var msg, warning, _i, _len;
        msg = "";
        for (_i = 0, _len = warningStack.length; _i < _len; _i++) {
          warning = warningStack[_i];
          msg += warning + "\n";
        }
        return console.error("Simulation Warning: " + msg);
      };

      CircuitCanvas.prototype.drawError = function(context) {
        var error, msg, _i, _len;
        msg = "";
        for (_i = 0, _len = errorStack.length; _i < _len; _i++) {
          error = errorStack[_i];
          msg += error + "\n";
        }
        return console.error("Simulation Error: " + msg);
      };

      CircuitCanvas.prototype.clear = function() {
        var _ref;
        return (_ref = this.Context) != null ? _ref.clear() : void 0;
      };

      CircuitCanvas.prototype.getContext = function() {
        return this.Context;
      };

      CircuitCanvas.prototype.getCanvas = function() {
        var _ref;
        return (_ref = this.Context) != null ? _ref.getCanvas() : void 0;
      };

      CircuitCanvas.prototype.getBuffer = function() {
        var _ref;
        return (_ref = this.Context) != null ? _ref.getCanvas().toBuffer : void 0;
      };

      CircuitCanvas.prototype.getMouseHandler = function() {
        return this.mouseHandler;
      };

      CircuitCanvas.prototype.getKeyHandler = function() {
        return this.keyHandler;
      };

      /* Event Listeners
      */


      CircuitCanvas.prototype.getMousePos = function(event) {
        var rect;
        rect = this.CanvasJQueryElm.get(0).getBoundingClientRect();
        return {
          x: event.clientX - rect.left,
          y: event.clientY - rect.top
        };
      };

      CircuitCanvas.prototype.onMouseMove = function(event) {
        var mousePos;
        mousePos = this.getMousePos(event);
        if (this.mouseHandler.isMouseDown()) {
          return this.mouseHandler.onMouseDrag(mousePos.x, mousePos.y);
        } else {
          return this.mouseHandler.onMouseMove(mousePos.x, mousePos.y);
        }
      };

      CircuitCanvas.prototype.onMouseDown = function(event) {
        var mousePos;
        mousePos = this.getMousePos(event);
        return this.mouseHandler.onMouseDown(mousePos.x, mousePos.y);
      };

      CircuitCanvas.prototype.onMouseUp = function(event) {
        var mousePos;
        mousePos = this.getMousePos(event);
        return this.mouseHandler.onMouseUp(mousePos.x, mousePos.y);
      };

      CircuitCanvas.prototype.onMouseClick = function(event) {
        var mousePos;
        mousePos = this.getMousePos(event);
        return this.mouseHandler.onMouseClick(mousePos.x, mousePos.y);
      };

      CircuitCanvas.prototype.repaint = function(Circuit) {
        return this.drawComponents();
      };

      return CircuitCanvas;

    })(Observer);
    return CircuitCanvas;
  });

}).call(this);
