// Generated by CoffeeScript 1.4.0
(function() {

  define(['cs!CanvasContext'], function(CanvasContext) {
    var CircuitRenderer;
    CircuitRenderer = (function() {

      function CircuitRenderer(Circuit, Canvas) {
        this.Circuit = Circuit;
        if (Canvas) {
          this.Context = new CanvasContext(Canvas);
        }
      }

      CircuitRenderer.prototype.drawComponents = function() {
        var component, _i, _len, _ref, _results;
        if (this.Context) {
          _ref = this.Circuit.getElements();
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            component = _ref[_i];
            _results.push(this.drawComponent(component));
          }
          return _results;
        }
      };

      CircuitRenderer.prototype.drawComponent = function(component) {
        if (this.Context) {
          return component.draw(this.Context);
        }
      };

      CircuitRenderer.prototype.drawInfo = function() {
        var bottomTextOffset, ybase;
        bottomTextOffset = 100;
        return ybase = this.Circuit.getCircuitBottom - (15 * 1) - bottomTextOffset;
      };

      CircuitRenderer.prototype.drawWarning = function(context) {
        var msg, warning, _i, _len;
        msg = "";
        for (_i = 0, _len = warningStack.length; _i < _len; _i++) {
          warning = warningStack[_i];
          msg += warning + "\n";
        }
        return console.error("Simulation Warning: " + msg);
      };

      CircuitRenderer.prototype.drawError = function(context) {
        var error, msg, _i, _len;
        msg = "";
        for (_i = 0, _len = errorStack.length; _i < _len; _i++) {
          error = errorStack[_i];
          msg += error + "\n";
        }
        return console.error("Simulation Error: " + msg);
      };

      CircuitRenderer.prototype.clear = function() {
        var _ref;
        return (_ref = this.Context) != null ? _ref.clear() : void 0;
      };

      CircuitRenderer.prototype.getContext = function() {
        return this.Context;
      };

      CircuitRenderer.prototype.getCanvas = function() {
        var _ref;
        return (_ref = this.Context) != null ? _ref.getCanvas() : void 0;
      };

      CircuitRenderer.prototype.getBuffer = function() {
        var _ref;
        return (_ref = this.Context) != null ? _ref.getCanvas().toBuffer : void 0;
      };

      return CircuitRenderer;

    })();
    return CircuitRenderer;
  });

}).call(this);
