// Generated by CoffeeScript 1.8.0
(function() {
  define(['cs!Circuit', 'cs!ArrayUtils'], function(Circuit, ArrayUtils) {
    return describe("Circuit Solver", function() {
      beforeEach(function() {
        this.Circuit = new Circuit();
        return this.Solver = this.Circuit.Solver;
      });
      return describe("on initialization", function() {
        it("should initiate solver", function() {
          this.Solver !== null;
          this.Solver.Stamper !== null;
          return this.Solver.scaleFactors.toString().should.equal(ArrayUtils.zeroArray(400).toString());
        });
        it("solver should belong to @Circuit", function() {
          this.Solver.Circuit.should.equal(this.Circuit);
          return this.Circuit.Solver.should.equal(this.Solver);
        });
        it("should have correct default values", function() {
          this.Solver.time.should.equal(0);
          this.Solver.converged.should.equal(true);
          this.Solver.circuitNonLinear.should.equal(false);
          this.Solver.subIterations === 5000;
          return this.Solver.analyzeFlag.should.equal(true);
        });
        return it("should have empty default matrix values", function() {
          this.Solver.circuitMatrix.should.be.empty;
          this.Solver.circuitRightSide.should.be.empty;
          this.Solver.origMatrix.should.be.empty;
          this.Solver.origRightSide.should.be.empty;
          this.Solver.circuitRowInfo.should.be.empty;
          return this.Solver.circuitPermute.should.be.empty;
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=circuitSolverTest.js.map
