// Generated by CoffeeScript 1.8.0
(function() {
  define(['cs!CircuitSolver', 'cs!Circuit'], function(CircuitSolver, Circuit) {
    return describe("Matrix Solver", function() {
      beforeEach(function() {
        this.Circuit = new Circuit();
        this.Solver = new CircuitSolver(this.Circuit);
        this.circuitPermute = [0, 0, 0];
        this.solvedMatrix = [[0, 0, 0], [0, 0, 0], [0, 0, 0]];
        return this.matrix3 = [[1, 2, 3], [4, 5, 6], [7, 8, 10]];
      });
      return describe("calling lu_factor", function() {
        beforeEach(function() {
          return this.result = this.Solver.luFactor(this.matrix3, 3, this.circuitPermute);
        });
        it("factors a 3x3 nonsingular array", function() {
          return this.result.should.equal(true);
        });
        it("initializes permute matrix", function() {});
        it("initializes solve matrix", function() {});
        it("returns false for a singular matrix", function() {});
        return describe("then calling lu_solve", function() {
          beforeEach(function() {
            return this.result = this.Solver.luSolve(this.matrix3, 3, this.circuitPermute, this.solvedMatrix);
          });
          it("solves circuit matrix", function() {});
          return it("doesn't modify circuitMatrix", function() {});
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=matrixSolverTest.js.map
