// Generated by CoffeeScript 1.4.0
(function() {

  define(['cs!MatrixStamper', 'cs!CircuitSolver', 'cs!Circuit'], function(MatrixStamper, CircuitSolver, Circuit) {
    return describe("Matrix stamper", function() {
      before(function() {
        this.Circuit = new Circuit();
        this.CircuitSolver = new CircuitSolver();
        return this.MatrixStamper = new MatrixStamper();
      });
      it("should stamp VCVS", function() {});
      it("should stamp Voltage Source", function() {});
      it("should stamp resistor", function() {});
      it("should stamp conductance", function() {});
      it("should stamp VCCurrentSource", function() {});
      it("should stamp CCCS", function() {});
      it("should stamp Matrix", function() {});
      it("should stamp right side", function() {});
      return it("should stamp nonlinear", function() {});
    });
  });

}).call(this);
