// Generated by CoffeeScript 1.4.0
(function() {

  define(['cs!ResistorElm', 'cs!Circuit'], function(ResistorElm, Circuit) {
    return describe("Resistor", function() {
      beforeEach(function() {
        this.Circuit = new Circuit();
        return this.resistor = new ResistorElm(100, 100, 100, 200, 0, [50]);
      });
      it("should have correct resistance", function() {
        return this.resistor.resistance.should.equal(50);
      });
      it("should not have any internal voltage sources", function() {
        return this.resistor.getVoltageSourceCount().should.equal(0);
      });
      it("should calculate current when voltage is applied", function() {
        this.resistor.getPostCount().should.equal(2);
        return this.resistor.getInternalNodeCount().should.equal(0);
      });
      it("should have correct dump type", function() {
        return this.resistor.getDumpType().should.equal("r");
      });
      it("should be orphaned", function() {
        return this.resistor.orphaned().should.equal(true);
      });
      return describe("after soldering to circuit", function() {
        beforeEach(function() {
          return this.Circuit.solder(this.resistor);
        });
        it("should not be orphaned", function() {
          return this.resistor.orphaned().should.equal(false);
        });
        return it("should be stampable", function() {
          return this.resistor.stamp(this.Circuit.Solver.Stamper);
        });
      });
    });
  });

}).call(this);
