// Generated by CoffeeScript 1.8.0
(function() {
  define(['cs!VoltageElm', 'cs!Circuit', 'cs!MatrixStamper'], function(VoltageElm, Circuit, MatrixStamper) {
    return describe("Voltage Component", function() {
      beforeEach(function() {
        this.Circuit = new Circuit();
        this.Stamper = new MatrixStamper(this.Circuit);
        return this.voltageElm = new VoltageElm(100, 100, 100, 200, 0, [0, 40, 5, 1, 90, .45]);
      });
      it("has correct defaults", function() {
        this.voltageElm.waveform.should.equal(VoltageElm.WF_DC);
        this.voltageElm.frequency.should.equal(40);
        this.voltageElm.maxVoltage.should.equal(5);
        this.voltageElm.bias.should.equal(1);
        this.voltageElm.phaseShift.should.equal(90);
        return this.voltageElm.dutyCycle.should.equal(0.45);
      });
      it("has correct number of posts", function() {
        this.voltageElm.getPostCount().should.equal(2);
        return this.voltageElm.getInternalNodeCount().should.equal(0);
      });
      it("is not have any internal voltage sources", function() {
        return this.voltageElm.getVoltageSourceCount().should.equal(1);
      });
      it("has correct dump type", function() {
        return this.voltageElm.getDumpType().should.equal("v");
      });
      it("has correct toString()", function() {
        return this.voltageElm.toString().should.equal("VoltageElm");
      });
      it("should be orphaned", function() {
        return this.voltageElm.orphaned().should.equal(true);
      });
      return describe("after soldering to circuit", function() {
        beforeEach(function() {
          return this.Circuit.solder(this.voltageElm);
        });
        it("should get voltage correctly", function() {
          return this.voltageElm.getVoltage().should.equal(6);
        });
        it("is not be orphaned", function() {
          return this.voltageElm.orphaned().should.equal(false);
        });
        it("should be stampable", function() {
          return this.voltageElm.stamp(this.Stamper);
        });
        it("should be steppable", function() {
          return this.voltageElm.doStep();
        });
        it("should be drawable", function() {});
        return it("should setPoints", function() {
          return this.voltageElm.setPoints();
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=voltageTest.js.map
