// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['cs!CircuitComponent', 'cs!DrawHelper', 'cs!Units', 'cs!Point'], function(CircuitComponent, DrawHelper, Units, Point) {
    var CapacitorElm;
    CapacitorElm = (function(_super) {

      __extends(CapacitorElm, _super);

      CapacitorElm.FLAG_BACK_EULER = 2;

      function CapacitorElm(xa, ya, xb, yb, f, st) {
        CircuitComponent.call(this, xa, ya, xb, yb, f);
        this.capacitance = 5e-6;
        this.compResistance = 0;
        this.voltDiff = 10;
        this.plate1 = [];
        this.plate2 = [];
        this.curSourceValue = 0;
        if (st) {
          if (typeof st === "string") {
            st = st.split(" ");
          }
          this.capacitance = Number(st[0]);
          this.voltdiff = Number(st[1]);
        }
      }

      CapacitorElm.prototype.isTrapezoidal = function() {
        return (this.flags & CapacitorElm.FLAG_BACK_EULER) === 0;
      };

      CapacitorElm.prototype.setNodeVoltage = function(n, c) {
        CapacitorElm.__super__.setNodeVoltage.apply(this, arguments).setNodeVoltage(n, c);
        return this.voltdiff = this.volts[0] - this.volts[1];
      };

      CapacitorElm.prototype.reset = function() {
        this.current = this.curcount = 0;
        return this.voltdiff = 1e-3;
      };

      CapacitorElm.prototype.getDumpType = function() {
        return "c";
      };

      CapacitorElm.prototype.dump = function() {
        return CircuitComponent.prototype.dump.call(this) + " " + this.capacitance + " " + this.voltdiff;
      };

      CapacitorElm.prototype.setPoints = function() {
        var f;
        CircuitComponent.prototype.setPoints.call(this);
        f = (this.dn / 2 - 4) / this.dn;
        this.lead1 = DrawHelper.interpPoint(this.point1, this.point2, f);
        this.lead2 = DrawHelper.interpPoint(this.point1, this.point2, 1 - f);
        this.plate1 = [new Point(), new Point()];
        this.plate2 = [new Point(), new Point()];
        DrawHelper.interpPoint(this.point1, this.point2, f, 12, this.plate1[0], this.plate1[1]);
        return DrawHelper.interpPoint(this.point1, this.point2, 1 - f, 12, this.plate2[0], this.plate2[1]);
      };

      CapacitorElm.prototype.draw = function(renderContext) {
        var color, hs;
        hs = 12;
        this.setBboxPt(this.point1, this.point2, hs);
        this.curcount = this.updateDotCount();
        if (!this.isBeingDragged()) {
          this.drawDots(this.point1, this.lead1, this.curcount);
          this.drawDots(this.point2, this.lead2, -this.curcount);
        }
        color = this.setVoltageColor(this.volts[0]);
        renderContext.drawThickLinePt(this.point1, this.lead1, color);
        this.setPowerColor(false);
        renderContext.drawThickLinePt(this.plate1[0], this.plate1[1], color);
        color = this.setVoltageColor(this.volts[1]);
        renderContext.drawThickLinePt(this.point2, this.lead2, color);
        this.setPowerColor(false);
        renderContext.drawThickLinePt(this.plate2[0], this.plate2[1], color);
        return this.drawPosts();
      };

      CapacitorElm.prototype.drawUnits = function() {
        var s;
        s = Units.getUnitText(this.capacitance, "F");
        return this.drawValues(s, hs);
      };

      CapacitorElm.prototype.stamp = function(stamper) {
        var Solver;
        Solver = this.getParentCircuit().Solver;
        if (this.isTrapezoidal()) {
          this.compResistance = Solver.timeStep / (2 * this.capacitance);
        } else {
          this.compResistance = Solver.timeStep / this.capacitance;
        }
        stamper.stampResistor(this.nodes[0], this.nodes[1], this.compResistance);
        stamper.stampRightSide(this.nodes[0]);
        return stamper.stampRightSide(this.nodes[1]);
      };

      CapacitorElm.prototype.startIteration = function() {
        if (this.isTrapezoidal()) {
          return this.curSourceValue = -this.voltdiff / this.compResistance - this.current;
        } else {
          return this.curSourceValue = -this.voltdiff / this.compResistance;
        }
      };

      CapacitorElm.prototype.calculateCurrent = function() {
        var voltdiff;
        voltdiff = this.volts[0] - this.volts[1];
        if (this.compResistance > 0) {
          return this.current = voltdiff / this.compResistance + this.curSourceValue;
        }
      };

      CapacitorElm.prototype.doStep = function() {
        var Circuit;
        Circuit = this.getParentCircuit();
        return Circuit.Solver.Stamper.stampCurrentSource(this.nodes[0], this.nodes[1], this.curSourceValue);
      };

      CapacitorElm.prototype.getInfo = function(arr) {
        var v;
        arr[0] = "capacitor";
        this.getBasicInfo(arr);
        arr[3] = "C = " + Units.getUnitText(this.capacitance, "F");
        arr[4] = "P = " + Units.getUnitText(this.getPower(), "W");
        v = this.getVoltageDiff();
        return arr[4] = "U = " + Units.getUnitText(.5 * this.capacitance * v * v, "J");
      };

      CapacitorElm.prototype.getEditInfo = function(n) {
        var ei;
        if (n === 0) {
          return new EditInfo("Capacitance (F)", this.capacitance, 0, 0);
        }
        if (n === 1) {
          ei = new EditInfo("", 0, -1, -1);
          ei.checkbox = "Trapezoidal Approximation";
          return ei;
        }
        return null;
      };

      CapacitorElm.prototype.setEditValue = function(n, ei) {
        if (n === 0 && ei.value > 0) {
          this.capacitance = ei.value;
        }
        if (n === 1) {
          if (ei.isChecked) {
            return this.flags &= ~CapacitorElm.FLAG_BACK_EULER;
          } else {
            return this.flags |= CapacitorElm.FLAG_BACK_EULER;
          }
        }
      };

      CapacitorElm.prototype.needsShortcut = function() {
        return true;
      };

      CapacitorElm.prototype.toString = function() {
        return "Capacitor";
      };

      return CapacitorElm;

    })(CircuitComponent);
    return CapacitorElm;
  });

}).call(this);
