// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['cs!Settings', 'cs!DrawHelper', 'cs!Polygon', 'cs!Rectangle', 'cs!Point', 'cs!CircuitComponent', 'cs!Units'], function(Settings, DrawHelper, Polygon, Rectangle, Point, CircuitComponent, Units) {
    var DiodeElm;
    DiodeElm = (function(_super) {

      __extends(DiodeElm, _super);

      DiodeElm.FLAG_FWDROP = 1;

      DiodeElm.DEFAULT_DROP = .805904783;

      function DiodeElm(xa, ya, xb, yb, f, st) {
        DiodeElm.__super__.constructor.call(this, xa, ya, xb, yb, f);
        this.hs = 8;
        this.poly;
        this.cathode = [];
        this.diode = new Diode();
        this.fwdrop = DiodeElm.DEFAULT_DROP;
        this.zvoltage = 0;
        if ((f & DiodeElm.FLAG_FWDROP) > 0) {
          try {
            this.fwdrop = parseFloat(st);
          } catch (_error) {}
        }
        this.setup();
      }

      DiodeElm.prototype.nonLinear = function() {
        return true;
      };

      DiodeElm.prototype.setup = function() {
        return this.diode.setup(this.fwdrop, this.zvoltage);
      };

      DiodeElm.prototype.getDumpType = function() {
        return "d";
      };

      DiodeElm.prototype.dump = function() {
        this.flags |= DiodeElm.FLAG_FWDROP;
        return CircuitComponent.prototype.dump.call(this) + " " + this.fwdrop;
      };

      DiodeElm.prototype.setPoints = function() {
        var pa;
        DiodeElm.__super__.setPoints.call(this);
        this.calcLeads(16);
        this.cathode = CircuitComponent.newPointArray(2);
        pa = CircuitComponent.newPointArray(2);
        DrawHelper.interpPoint(this.lead1, this.lead2, 0, this.hs, pa[0], pa[1]);
        DrawHelper.interpPoint(this.lead1, this.lead2, 1, this.hs, this.cathode[0], this.cathode[1]);
        return this.poly = CircuitComponent.createPolygon(pa[0], pa[1], this.lead2);
      };

      DiodeElm.prototype.draw = function() {
        this.drawDiode();
        this.doDots();
        return this.drawPosts();
      };

      DiodeElm.prototype.reset = function() {
        this.diode.reset();
        return this.volts[0] = this.volts[1] = this.curcount = 0;
      };

      DiodeElm.prototype.drawDiode = function() {
        var color, v1, v2;
        this.setBboxPt(this.point1, this.point2, this.hs);
        v1 = this.volts[0];
        v2 = this.volts[1];
        this.draw2Leads();
        color = this.setVoltageColor(v1);
        CircuitComponent.drawThickPolygonP(this.poly, color);
        color = this.setVoltageColor(v2);
        return CircuitComponent.drawThickLinePt(this.cathode[0], this.cathode[1], color);
      };

      DiodeElm.prototype.stamp = function() {
        return this.diode.stamp(this.nodes[0], this.nodes[1]);
      };

      DiodeElm.prototype.doStep = function() {
        return this.diode.doStep(this.volts[0] - this.volts[1]);
      };

      DiodeElm.prototype.calculateCurrent = function() {
        return this.current = this.diode.calculateCurrent(this.volts[0] - this.volts[1]);
      };

      DiodeElm.prototype.getInfo = function(arr) {
        arr[0] = "diode";
        arr[1] = "I = " + CircuitComponent.getCurrentText(this.getCurrent());
        arr[2] = "Vd = " + CircuitComponent.getVoltageText(this.getVoltageDiff());
        arr[3] = "P = " + CircuitComponent.getUnitText(this.getPower(), "W");
        return arr[4] = "Vf = " + CircuitComponent.getVoltageText(this.fwdrop);
      };

      DiodeElm.prototype.getEditInfo = function(n) {
        if (n === 0) {
          return new EditInfo("Fwd Voltage @ 1A", this.fwdrop, 10, 1000);
        }
      };

      DiodeElm.prototype.setEditValue = function(n, ei) {
        this.fwdrop = ei.value;
        return this.setup();
      };

      DiodeElm.prototype.needsShortcut = function() {
        return true;
      };

      return DiodeElm;

    })(CircuitComponent);
    return DiodeElm;
  });

}).call(this);
