// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['cs!Settings', 'cs!DrawHelper', 'cs!Polygon', 'cs!Rectangle', 'cs!Point', 'cs!CircuitComponent', 'cs!Units'], function(Settings, DrawHelper, Polygon, Rectangle, Point, CircuitComponent, Units) {
    var OutputElm;
    OutputElm = (function(_super) {

      __extends(OutputElm, _super);

      OutputElm.FLAG_VALUE = 1;

      function OutputElm(xa, ya, xb, yb, f, st) {
        OutputElm.__super__.constructor.call(this, xa, ya, xb, yb, f);
      }

      OutputElm.prototype.getDumpType = function() {
        return "O";
      };

      OutputElm.prototype.getPostCount = function() {
        return 1;
      };

      OutputElm.prototype.setPoints = function() {
        CircuitComponent.prototype.setPoints.call(this);
        return this.lead1 = new Point();
      };

      OutputElm.prototype.draw = function() {
        var color, s, selected;
        selected = this.needsHighlight() || Circuit.plotYElm === this;
        color = (selected ? CircuitComponent.selectColor : CircuitComponent.whiteColor);
        s = ((this.flags & OutputElm.FLAG_VALUE) !== 0 ? CircuitComponent.getVoltageText(this.volts[0]) : "out");
        if (this === Circuit.plotXElm) {
          s = "X";
        }
        if (this === Circuit.plotYElm) {
          s = "Y";
        }
        DrawHelper.interpPoint(this.point1, this.point2, this.lead1, 1 - (3 * s.length / 2 + 8) / this.dn);
        this.setBboxPt(this.point1, this.lead1, 0);
        this.drawCenteredText(s, this.x2, this.y2, true);
        color = this.setVoltageColor(this.volts[0]);
        if (selected) {
          color = Settings.SELECT_COLOR;
        }
        CircuitComponent.drawThickLinePt(this.point1, this.lead1, color);
        return this.drawPosts();
      };

      OutputElm.prototype.getVoltageDiff = function() {
        return this.volts[0];
      };

      OutputElm.prototype.getInfo = function(arr) {
        arr[0] = "output";
        return arr[1] = "V = " + CircuitComponent.getVoltageText(this.volts[0]);
      };

      OutputElm.prototype.getEditInfo = function(n) {
        var ei;
        if (n === 0) {
          ei = new EditInfo("", 0, -1, -1);
          ei.checkbox = "Show Voltage";
          return ei;
        }
        return null;
      };

      OutputElm.prototype.setEditValue = function(n, ei) {};

      return OutputElm;

    })(CircuitComponent);
    return OutputElm;
  });

}).call(this);
