// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['cs!Settings', 'cs!DrawHelper', 'cs!Polygon', 'cs!Rectangle', 'cs!Point', 'cs!CircuitComponent', 'cs!Units'], function(Settings, DrawHelper, Polygon, Rectangle, Point, CircuitComponent, Units) {
    var ProbeElm;
    ProbeElm = (function(_super) {

      __extends(ProbeElm, _super);

      ProbeElm.FLAG_SHOWVOLTAGE = 1;

      function ProbeElm(xa, ya, xb, yb, f, st) {
        ProbeElm.__super__.constructor.call(this, xa, ya, xb, yb, f);
      }

      ProbeElm.prototype.getDumpType = function() {
        return "p";
      };

      ProbeElm.prototype.setPoints = function() {
        var x;
        CircuitComponent.prototype.setPoints.call(this);
        if (this.point2.y < this.point1.y) {
          x = this.point1;
          this.point1 = this.point2;
          this.point2 = this.x1;
        }
        return this.center = DrawHelper.interpPoint(this.point1, this.point2, .5);
      };

      ProbeElm.prototype.draw = function() {
        var color, f, hs, len, s, selected;
        hs = 8;
        CircuitComponent.setBboxPt(this.point1, this.point2, hs);
        selected = this.needsHighlight() || Circuit.plotYElm === this;
        len = (selected || Circuit.dragElm === this ? 16 : this.dn - 32);
        CircuitComponent.calcLeads(Math.floor(len));
        color = this.setVoltageColor(this.volts[0]);
        if (selected) {
          color = CircuitComponent.selectColor;
        }
        CircuitComponent.drawThickLinePt(this.point1, this.lead1, color);
        color = this.setVoltageColor(this.volts[1]);
        if (selected) {
          CircuitComponent.setColor(this.selectColor);
        }
        CircuitComponent.drawThickLinePt(this.lead2, this.point2);
        f = new Font("SansSerif", Font.BOLD, 14);
        CircuitComponent.setFont(f);
        if (this === Circuit.plotXElm) {
          CircuitComponent.drawCenteredText("X", this.center.x1, this.center.y, color);
        }
        if (this === Circuit.plotYElm) {
          CircuitComponent.drawCenteredText("Y", this.center.x1, this.center.y, color);
        }
        if (this.mustShowVoltage()) {
          s = CircuitComponent.getShortUnitText(volts[0], "V");
          this.drawValues(s, 4);
        }
        return this.drawPosts();
      };

      ProbeElm.prototype.mustShowVoltage = function() {
        return (this.flags & ProbeElm.FLAG_SHOWVOLTAGE) !== 0;
      };

      ProbeElm.prototype.getInfo = function(arr) {
        arr[0] = "scope probe";
        return arr[1] = "Vd = " + CircuitComponent.getVoltageText(this.getVoltageDiff());
      };

      ProbeElm.prototype.getConnection = function(n1, n2) {
        return false;
      };

      ProbeElm.prototype.getEditInfo = function(n) {
        var ei;
        if (n === 0) {
          ei = new EditInfo("", 0, -1, -1);
          ei.checkbox = new Checkbox("Show Voltage", this.mustShowVoltage());
          return ei;
        }
        return null;
      };

      ProbeElm.prototype.setEditValue = function(n, ei) {
        var flags;
        if (n === 0) {
          if (ei.checkbox.getState()) {
            return flags = ProbeElm.FLAG_SHOWVOLTAGE;
          } else {
            return flags &= ~ProbeElm.FLAG_SHOWVOLTAGE;
          }
        }
      };

      return ProbeElm;

    })(CircuitComponent);
    return ProbeElm;
  });

}).call(this);
