// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['cs!Settings', 'cs!DrawHelper', 'cs!Polygon', 'cs!Rectangle', 'cs!Point', 'cs!CircuitComponent', 'cs!Units'], function(Settings, DrawHelper, Polygon, Rectangle, Point, CircuitComponent, Units) {
    var SwitchElm;
    SwitchElm = (function(_super) {

      __extends(SwitchElm, _super);

      function SwitchElm(xa, ya, xb, yb, f, st) {
        var str;
        SwitchElm.__super__.constructor.call(this, xa, ya, xb, yb, f, st);
        this.momentary = false;
        this.position = 0;
        this.posCount = 2;
        this.ps = new Point(0, 0);
        CircuitComponent.ps2 = new Point(0, 0);
        if (st) {
          if (typeof st === "string") {
            st = st.split(" ");
          }
          str = st[0];
          if (str === "true") {
            this.position = (this instanceof LogicInputElm ? 0 : 1);
          } else if (str === "false") {
            this.position = (this instanceof LogicInputElm ? 1 : 0);
          } else {
            this.position = parseInt(str);
          }
          this.momentary = st[1].toLowerCase() === "true";
        }
        this.posCount = 2;
      }

      SwitchElm.prototype.getDumpType = function() {
        return "s";
      };

      SwitchElm.prototype.dump = function() {
        return CircuitComponent.prototype.dump.call(this) + " " + this.position + " " + this.momentary;
      };

      SwitchElm.prototype.setPoints = function() {
        CircuitComponent.prototype.setPoints.call(this);
        this.calcLeads(32);
        this.ps = new Point(0, 0);
        return CircuitComponent.ps2 = new Point(0, 0);
      };

      SwitchElm.prototype.draw = function(renderContext) {
        var hs1, hs2, openhs;
        openhs = 16;
        hs1 = (this.position === 1 ? 0 : 2);
        hs2 = (this.position === 1 ? openhs : 2);
        this.setBboxPt(this.point1, this.point2, openhs);
        this.draw2Leads();
        if (this.position === 0) {
          this.doDots();
        }
        DrawHelper.interpPoint(this.lead1, this.lead2, this.ps, 0, hs1);
        DrawHelper.interpPoint(this.lead1, this.lead2, CircuitComponent.ps2, 1, hs2);
        CircuitComponent.drawThickLinePt(this.ps, CircuitComponent.ps2, Settings.FG_COLOR);
        return this.drawPosts();
      };

      SwitchElm.prototype.calculateCurrent = function() {
        if (this.position === 1) {
          return this.current = 0;
        }
      };

      SwitchElm.prototype.stamp = function() {
        if (this.position === 0) {
          return Circuit.stampVoltageSource(this.nodes[0], this.nodes[1], this.voltSource, 0);
        }
      };

      SwitchElm.prototype.getVoltageSourceCount = function() {
        if (this.position === 1) {
          return 0;
        } else {
          return 1;
        }
      };

      SwitchElm.prototype.mouseUp = function() {
        if (this.momentary) {
          return this.toggle();
        }
      };

      SwitchElm.prototype.toggle = function() {
        this.position++;
        if (this.position >= this.posCount) {
          return this.position = 0;
        }
      };

      SwitchElm.prototype.getInfo = function(arr) {
        arr[0] = (this.momentary ? "push switch (SPST)" : "switch (SPST)");
        if (this.position === 1) {
          arr[1] = "open";
          return arr[2] = "Vd = " + CircuitComponent.getVoltageDText(this.getVoltageDiff());
        } else {
          arr[1] = "closed";
          arr[2] = "V = " + CircuitComponent.getVoltageText(this.volts[0]);
          return arr[3] = "I = " + CircuitComponent.getCurrentDText(this.getCurrent());
        }
      };

      SwitchElm.prototype.getConnection = function(n1, n2) {
        return this.position === 0;
      };

      SwitchElm.prototype.isWire = function() {
        return true;
      };

      SwitchElm.prototype.getEditInfo = function(n) {};

      SwitchElm.prototype.setEditValue = function(n, ei) {
        return n === 0;
      };

      SwitchElm.prototype.toString = function() {
        return "SwitchElm";
      };

      return SwitchElm;

    })(CircuitComponent);
    return SwitchElm;
  });

}).call(this);
