// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['cs!Settings', 'cs!DrawHelper', 'cs!Polygon', 'cs!Rectangle', 'cs!Point', 'cs!CircuitComponent', 'cs!Units'], function(Settings, DrawHelper, Polygon, Rectangle, Point, CircuitComponent, Units) {
    var VarRailElm;
    VarRailElm = (function(_super) {

      __extends(VarRailElm, _super);

      function VarRailElm(xa, ya, xb, yb, f, st) {
        VarRailElm.__super__.constructor.call(this, xa, ya, xb, yb, f, st);
        this.sliderText = "voltage";
        this.frequency = this.maxVoltage;
        this.createSlider();
      }

      VarRailElm.prototype.dump = function() {
        return RailElm.prototype.dump.call(this) + " " + this.sliderText;
      };

      VarRailElm.prototype.getDumpType = function() {
        return 172;
      };

      VarRailElm.prototype.createSlider = function() {};

      VarRailElm.prototype.getVoltage = function() {
        var frequency;
        frequency = slider.getValue() * (maxVoltage - bias) / 100.0 + bias;
        return frequency;
      };

      VarRailElm.prototype.destroy = function() {
        Circuit.main.remove(label);
        return Circuit.main.remove(slider);
      };

      VarRailElm.prototype.getEditInfo = function(n) {
        var ei;
        if (n === 0) {
          return new EditInfo("Min Voltage", bias, -20, 20);
        }
        if (n === 1) {
          return new EditInfo("Max Voltage", maxVoltage, -20, 20);
        }
        if (n === 2) {
          ei = new EditInfo("Slider Text", 0, -1, -1);
          ei.text = sliderText;
          return ei;
        }
        return null;
      };

      VarRailElm.prototype.setEditValue = function(n, ei) {
        var bias, maxVoltage, sliderText;
        if (n === 0) {
          bias = ei.value;
        }
        if (n === 1) {
          maxVoltage = ei.value;
        }
        if (n === 2) {
          sliderText = ei.textf.getText();
          return label.setText(sliderText);
        }
      };

      return VarRailElm;

    })(RailElm);
    return VarRailElm;
  });

}).call(this);
