// Generated by CoffeeScript 1.8.0
(function() {
  define(['cs!CircuitNode', 'cs!CircuitLoader'], function(CircuitNode, CircuitLoader) {
    return describe("CircuitLoader", function() {
      return describe("should read voltdividesimple.json and", function() {
        before(function(done) {
          return CircuitLoader.createCircuitFromJSON("../../circuits/voltdividesimple.json", (function(_this) {
            return function(circuit) {
              _this.circuit = circuit;
              return done();
            };
          })(this));
        });
        it("have only 7 elements", function() {
          return this.circuit.numElements().should.equal(7);
        });
        return describe("should load parameters", function() {
          it("has correct completionStatus", function() {
            return this.circuit.Params.completionStatus.should.equal("complete");
          });
          it("has correct currentSpeed", function() {
            return this.circuit.Params.currentSpeed.should.equal(63.0);
          });
          it("has correct description", function() {
            return this.circuit.Params.description.should.equal("A simple voltage divider circuit");
          });
          it("has correct flags", function() {
            return this.circuit.Params.flags.should.equal(1);
          });
          it("has correct unique name", function() {
            console.log(this.circuit.Params.name);
            return this.circuit.Params.name.should.equal("voltdivide.txt");
          });
          it("has correct power range", function() {
            return this.circuit.Params.powerRange.should.equal(62.0);
          });
          it("has correct simSpeed", function() {
            return this.circuit.Params.simSpeed.should.equal(10.0);
          });
          it("has correct timeStep", function() {
            return this.circuit.Params.timeStep.should.equal(5.0e-6);
          });
          it("has correct title", function() {
            return this.circuit.Params.title.should.equal("Voltage Divider");
          });
          it("has correct topic", function() {
            return this.circuit.Params.topic.should.equal("Basics");
          });
          return it("has correct voltage_range", function() {
            return this.circuit.Params.voltageRange.should.equal(10.0);
          });
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=circuitLoaderTest.js.map
