// Generated by CoffeeScript 1.8.0
(function() {
  var Circuit, CircuitLoader, CircuitNode, fs;

  CircuitLoader = require("../../src/io/circuitLoader");

  Circuit = require("../../src/core/circuit");

  CircuitNode = require("../../src/core/nodeGraph/circuitNode").CircuitNode;

  fs = require('fs');

  describe("CircuitLoader", function() {
    before(function() {
      return this.circuit = new Circuit();
    });
    return describe("should read voltdividesimple.json and", function() {
      before(function(done) {
        CircuitLoader.readCircuitFromFile(this.circuit, "./circuits/voltdividesimple.json", (function(_this) {
          return function() {};
        })(this));
        return done();
      });
      it("have only 7 elements", function() {
        return this.circuit.numElements().should.equal(7);
      });
      it("should render circuit", function(done) {
        this.circuit.renderCircuit();
        return this.circuit.getRenderer().getCanvas().toBuffer(function(err, buf) {
          if (err) {
            throw err;
          }
          fs.writeFile(__dirname + '/render/voltDivideSimple.png', buf);
          return done();
        });
      });
      return describe("should load parameters", function() {
        it("should have correct completionStatus", function() {
          return this.circuit.Params.completionStatus.should.equal("complete");
        });
        it("should have correct currentSpeed", function() {
          return this.circuit.Params.currentSpeed.should.equal(63.0);
        });
        it("should have correct description", function() {
          return this.circuit.Params.description.should.equal("A simple voltage divider circuit");
        });
        it("should have correct flags", function() {
          return this.circuit.Params.flags.should.equal(1);
        });
        it("should have correct unique name", function() {
          console.log(this.circuit.Params.name);
          return this.circuit.Params.name.should.equal("voltdivide.txt");
        });
        it("should have correct power range", function() {
          return this.circuit.Params.powerRange.should.equal(62.0);
        });
        it("should have correct simSpeed", function() {
          return this.circuit.Params.simSpeed.should.equal(10.0);
        });
        it("should have correct timeStep", function() {
          return this.circuit.Params.timeStep.should.equal(5.0e-6);
        });
        it("should have correct title", function() {
          return this.circuit.Params.title.should.equal("Voltage Divider");
        });
        it("should have correct topic", function() {
          return this.circuit.Params.topic.should.equal("Basics");
        });
        return it("should have correct voltage_range", function() {
          return this.circuit.Params.voltageRange.should.equal(10.0);
        });
      });
    });
  });

}).call(this);

//# sourceMappingURL=loadCircuitTest.js.map
