// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    var ColorMapState;
    ColorMapState = (function() {

      function ColorMapState() {}

      ColorMapState.SHOW_POWER = "SHOW_POWER";

      ColorMapState.SHOW_VOLTAGE = "SHOW_VOLTAGE";

      return ColorMapState;

    })();
    return ColorMapState;
  });

}).call(this);
