// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    var KeyboardState;
    KeyboardState = (function() {

      function KeyboardState() {}

      KeyboardState.NO_KEY_DOWN = 0;

      KeyboardState.KEY_DELETE = 46;

      KeyboardState.KEY_SHIFT = 16;

      KeyboardState.KEY_CTRL = 17;

      KeyboardState.KEY_ALT = 18;

      KeyboardState.KEY_ESC = 27;

      KeyboardState.prototype.keyDown = KeyboardState.NO_KEY_DOWN;

      return KeyboardState;

    })();
    return KeyboardState;
  });

}).call(this);
