// Generated by CoffeeScript 1.4.0
(function() {

  define([], function() {
    var MouseState;
    MouseState = (function() {
      var dragElm, dragging, menuElm;

      function MouseState() {}

      MouseState.MODE_ADD_ELM = "MODE_ADD_ELM";

      MouseState.MODE_DRAG_ALL = "MODE_DRAG_ALL";

      MouseState.MODE_DRAG_ROW = "MODE_DRAG_ROW";

      MouseState.MODE_DRAG_COLUMN = "MODE_DRAG_COLUMN";

      MouseState.MODE_DRAG_SELECTED = "MODE_DRAG_SELECTED";

      MouseState.MODE_DRAG_POST = "MODE_DRAG_POST";

      MouseState.MODE_SELECT = "MODE_SELECT";

      MouseState.prototype.mouseMode = MouseState.MODE_SELECT;

      MouseState.LEFT_MOUSE_BTN = 0;

      MouseState.MIDDLE_MOUSE_BTN = 1;

      MouseState.RIGHT_MOUSE_BTN = 2;

      MouseState.NO_MOUSE_BTN = 3;

      MouseState.prototype.mouseButtonDown = MouseState.NO_MOUSE_BTN;

      MouseState.prototype.dragX = 0;

      MouseState.prototype.dragY = 0;

      MouseState.prototype.initDragX = 0;

      MouseState.prototype.initDragY = 0;

      dragElm = null;

      menuElm = null;

      dragging = false;

      MouseState.prototype.isDragging = function() {
        return dragging;
      };

      return MouseState;

    })();
    return MouseState;
  });

}).call(this);
