// Generated by CoffeeScript 1.4.0
(function() {

  define(['cs!fs', 'cs!CanvasContext'], function(fs, CanvasContext) {});

  describe("Canvas Context", function() {
    beforeEach(function(done) {
      this.canvasContext = new CanvasContext(400, 300);
      this.canvasContext.clear();
      return done();
    });
    it("should render (46, 32):   10px radius red circle  3px border  fill: #F38   stroke: #0F0601", function(done) {
      this.canvasContext.fillCircle(46, 32, 10, 3, '#F38', '#0F0601');
      return this.canvasContext.getCanvas().toBuffer(function(err, buf) {
        if (err) {
          throw err;
        }
        fs.writeFile(__dirname + '/primitives/circle.png', buf);
        return done();
      });
    });
    it("should render (46, 32, 100, 150):  #00A", function(done) {
      this.canvasContext.drawThickLine(46, 32, 100, 150, '#00A');
      return this.canvasContext.getCanvas().toBuffer(function(err, buf) {
        if (err) {
          throw err;
        }
        fs.writeFile(__dirname + '/primitives/line.png', buf);
        return done();
      });
    });
    it("should render polygon:  [46, 32, 100, 150], [150, 46, 32, 100] #0CA", function(done) {
      this.canvasContext.drawThickPolygon([46, 32, 100, 150], [150, 46, 32, 100], '#0CA');
      return this.canvasContext.getCanvas().toBuffer(function(err, buf) {
        if (err) {
          throw err;
        }
        fs.writeFile(__dirname + '/primitives/poly.png', buf);
        return done();
      });
    });
    return it("should clear canvas", function(done) {
      return this.canvasContext.getCanvas().toBuffer(function(err, buf) {
        if (err) {
          throw err;
        }
        fs.writeFile(__dirname + '/primitives/clear.png', buf);
        return done();
      });
    });
  });

}).call(this);
