// Generated by CoffeeScript 1.4.0
(function() {

  define(['cs!fs', 'cs!Canvas'], function(fs, Canvas) {
    return describe("Canvas", function() {
      before(function() {
        this.canvas = new Canvas(400, 300);
        return this.context = this.canvas.getContext('2d');
      });
      return it("should draw line", function() {
        this.context.beginPath();
        this.context.fillStyle = "#FA6B00";
        this.context.fillRect(50, 60, 90, 70);
        return this.canvas.toBuffer(function(err, buf) {
          if (err) {
            throw err;
          }
          return fs.writeFile(__dirname + '/primitives/block.png', buf);
        });
      });
    });
  });

}).call(this);
