// Generated by CoffeeScript 1.4.0
(function() {

  define(['cs!DrawHelper', 'cs!Point'], function(DrawHelper, Point) {
    return describe("Draw Helpers Test", function() {
      return it("interpolates between two points", function() {});
    });
  });

}).call(this);
