// Generated by CoffeeScript 1.4.0

/*
Stores Environment-specific settings

These are the global settings for Maxwell and should defined by the user.
Settings do not change by loading a new circuit.
*/


(function() {

  define(['cs!ColorPalette'], function(ColorPalette) {
    var Settings;
    Settings = (function() {

      function Settings() {}

      Settings.SPEED = 112;

      Settings.FRACTIONAL_DIGITS = 2;

<<<<<<< HEAD
      Settings.POST_RADIUS = 3;

      Settings.CURRENT_RADIUS = 3;

      Settings.LINE_WIDTH = 2;

      Settings.GRID_SIZE = 16;
=======
      Settings.CURRENT_SEGMENT_LENGTH = 16;

      Settings.POST_RADIUS = 3;

      Settings.CURRENT_RADIUS = 2;

      Settings.LINE_WIDTH = 1;

      Settings.GRID_SIZE = 5;
>>>>>>> reorganize_packages

      Settings.SMALL_GRID = false;

      Settings.SELECT_COLOR = ColorPalette.orange;

      Settings.POST_COLOR_SELECTED = ColorPalette.orange;

      Settings.POST_COLOR = ColorPalette.black;

      Settings.DOTS_COLOR = ColorPalette.yellow;

      Settings.DOTS_OUTLINE = ColorPalette.orange;

      Settings.TEXT_COLOR = ColorPalette.black;

      Settings.TEXT_ERROR_COLOR = ColorPalette.red;

      Settings.TEXT_WARNING_COLOR = ColorPalette.yellow;

      Settings.SELECTION_MARQUEE_COLOR = ColorPalette.orange;

      Settings.GRID_COLOR = ColorPalette.darkyellow;

      Settings.BG_COLOR = ColorPalette.white;

      Settings.FG_COLOR = ColorPalette.darkgray;

      Settings.ERROR_COLOR = ColorPalette.darkred;

      Settings.WARNING_COLOR = ColorPalette.orange;

      return Settings;

    })();
    return Settings;
  });

}).call(this);
