// Generated by CoffeeScript 1.4.0
(function() {

  define(['cs!WireElm', 'cs!ResistorElm', 'cs!GroundElm', 'cs!VoltageElm', 'cs!Oscilloscope'], function(WireElm, ResistorElm, GroundElm, VoltageElm, Oscilloscope) {
    var ComponentRegistry;
    ComponentRegistry = (function() {

      function ComponentRegistry() {}

      ComponentRegistry.DumpTypeConversions = {
        'r': 'ResistorElm',
        'w': 'WireElm',
        'g': 'GroundElm',
        'v': 'VoltageElm'
      };

      ComponentRegistry.ComponentDefs = {
        'w': WireElm,
        'r': ResistorElm,
        'g': GroundElm,
        'v': VoltageElm
      };

      ComponentRegistry.registerAll = function() {
        var Component, _i, _len, _ref, _results;
        _ref = this.ComponentDefs;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          Component = _ref[_i];
          if (process.env.NODE_ENV === 'development') {
            console.log("Registering Element: " + Component.prototype + " ");
          }
          _results.push(this.register(Component));
        }
        return _results;
      };

      ComponentRegistry.register = function(componentConstructor) {
        var dumpClass, dumpType, newComponent;
        try {
          newComponent = new componentConstructor(0, 0, 0, 0, 0, null);
          dumpType = newComponent.getDumpType();
          dumpClass = componentConstructor;
          if (this.dumpTypes[dumpType] === dumpClass) {
            console.log("" + componentConstructor + " is a dump class");
            return;
          }
          if (this.dumpTypes[dumpType] != null) {
            console.log("Dump type conflict: " + dumpType + " " + this.dumpTypes[dumpType]);
            return;
          }
          return this.dumpTypes[dumpType] = componentConstructor;
        } catch (e) {
          if (process.env.NODE_ENV === 'development') {
            return Logger.warn("Element: " + componentConstructor.prototype + " Not yet implemented: [" + e.message + "]");
          }
        }
      };

      return ComponentRegistry;

    })();
    return ComponentRegistry;
  });

}).call(this);
