// Generated by CoffeeScript 1.8.0
(function() {
  define(['cs!Maxwell'], function(Maxwell) {
    return describe("Maxwell", function() {
      it("can build a circuit from a JSON file", function() {
        return Maxwell.createCircuit(this.circuitName);
      });
      return it("can build a circuit from raw JSON data", function() {
        return Maxwell.createCircuit(this.circuitName);
      });
    });
  });

}).call(this);

//# sourceMappingURL=linearCircuitTest.js.map
