module.exports = class Config {
  CURRENT_TYPE_DOTS = 'DOTS';
  CURENT_TYPE_DOTS = 'DOTS';
  CURRENT_TYPE_DASHES = 'DASHES';
  CURENT_TYPE_DASHES = 'DASHES';

  FRACTIONAL_DIGITS = 2;
  CURRENT_SEGMENT_LENGTH = 16;
  WIRE_POSTS = true;

  // LINE WIDTHS:
  POST_RADIUS = 2;
  POST_OUTLINE_SIZE = 1;
  CURRENT_RADIUS = 2;
  CURRENT_COLOR = 'rgba(255, 255, 255, 0.7)';
  LINE_WIDTH = 2;
  POLY_LINE_WIDTH = 1;
  BOLD_LINE_WIDTH = 4;

  // GRID
  GRID_SIZE = 8;

  SHOW_VALUES = false;

  TEXT_STROKE_COLOR = '#FFF';

  CURRENT_DISPLAY_TYPE = 'DASHES';

  SELECT_COLOR = '#573400';
  HIGHLIGHT_COLOR = '#FF4500';

  LIGHT_POST_COLOR = '#333';
  POST_COLOR = '#000';
  OUTLINE_COLOR = '#666';
  POST_SELECT_COLOR = '#FF8C00';
  POST_SELECT_OUTLINE_COLOR = '#F0F';

  DOTS_COLOR = '#FF0';
  DOTS_OUTLINE = '#FFA500';

  CHIP_OUTLINE_WIDTH = 0;

  TEXT_COLOR = '#000';
  TEXT_ERROR_COLOR = '#F00';
  TEXT_WARNING_COLOR = '#FF0';

  TEXT_SIZE = 7.5;
  FONT = 'MONACO';
  TEXT_STYLE = 'BOLD';
  LABEL_COLOR = '#0000CD';
  PIN_LABEL_COLOR = '#444';
  SECONDARY_COLOR = '#777';

  SELECTION_MARQUEE_COLOR = '#FFA500';

  GREY = '#666';
  GRAY = '#666';

  COMPONENT_DECIMAL_PLACES = 1;

  GRID_COLOR = '#F0F';
  SWITCH_COLOR = '#666';
  FILL_COLOR = '#FFF';
  BG_COLOR = '#FFF';
  FG_COLOR = '#FFF';
  STROKE_COLOR = '#000';
  ERROR_COLOR = '#8B0000';
  WARNING_COLOR = '#FFA500';
};
